---
title: "ph_time_series2"
author: "Ryan Wang"
date: "7/12/2022"
output: html_document
---

```{r setup, include=FALSE, messsage = FALSE, warning= FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(scales)
library(dplyr)
library('xts') # use to convert dataframe to time series
library(zoo)
library(lmtest)
library(forecast)

library(fUnitRoots)
```

```{r}
ph_<-read.csv('C:/Users/Ryan_/Documents/R/time series/files/ph_across_sites.csv')

lol <- ph_[ph_$site=="Lompoc Landing",c(1,2,3,7)]
y=strptime("2021-06-14 11:30:00","%Y-%m-%d %H:%M:%S")+900*1:8826 # 15 minutes time interval.
power=ts(lol[1:500,4],y) # Convert the dataframe to time series object.
total=ts(lol[,4],y)
plot(total)
```

```{r}
##### 2.1 stationarity test #####
plot(total)
# The variance is not constant. Not stationary.

##### 2.2 acf-autocorrelation test #####

acf(total,lag.max = 960)
pacf(total, lag.max = 960)

acf(power, lag.max = 100)
# The autocorrelation has periodic fluctuation and decay slowly. Not stationary.

##### 2.3 adf-Unit root test #####
adfTest(as.numeric(y1))
adf.test(as.numeric(y))
Box.test(total,type = "Ljung-Box",lag=6)
# 0.576>0.05, fail to reject the null. Unit root exists. The times series is non-stationary.

##### 2.4 First difference #####
y1 <- diff(total)
frequency(y1)
plot(y1)
adf.test(as.numeric(y1)) # The time series becomes stationary after taking the first difference.
acf(y1,lag.max=96*10) # The time series show seasonality.
acf(y1, lag.max=300)

pacf(y1,lag.max=960)# Many significant spikes at the beginning and decay exponentially. So q = 0.
pacf(y1,lag.max=300)


##### 2.5 White noise test #####
Box.test(y1,type = "Ljung-Box",lag=6)
# 2.2e-16 <0.05 , reject the null, the time series is not a white noise.
# There is no correlation in a white noise series. No need to fit a model.

for (i in 1:5) {print(Box.test(y1,lag = 96*i , type = "Ljung-Box"))}
# 2.2e-16 <0.05 , reject the null, the time series is not a white noise.
```

```{r}
#### 3.modelling ####
auto.arima(ts(total, frequency = 72),D=1)
model_lol0 <- arima(total,order=c(5,0,0), seasonal = list(order=c(0,1,0),period=75))
model_lol0$residuals

model_lol <- arima(power,order=c(0,1,5),seasonal = list(order=c(0,1,2),period=75))
model_lol_2 <- arima(power,order=c(0,1,4),seasonal = list(order=c(0,1,1),period=71))

AIC(model_lol)
AIC(model_lol_2)
##### Test the model #####
tsdiag(model_lol_2)
acf(model_lol$residuals, lag.max = 80)
acf(model_lol_2$residuals, lag.max = 80)
# Standardized residuals plot:
# The residuals have zero mean. If the residuals have a mean other than zero, then the forecasts are biased.

# ACF plot of the residual:
# The residuals are uncorrelated. If there are correlations between residuals, then there is information left in the residuals which should be used in computing forecasts.

# Ljung-Box test:
# H0: The residuals are independently distributed.
# HA: The residuals are not independently distributed; they exhibit serial correlation.

Box.test(model_lol$residuals,lag=6)
# p-value = 0.9485. Fail to reject the null, the residual of the model is a white noise.

coeftest(model_lol)
# p-values are lower than 0.05. 


#### 4.Prediction ####
x_forecast <- forecast::forecast(model_lol,h=4*12,level=c(0.8,0.95))
plot(x_forecast)
x_forecast
x_forecast_2<- forecast::forecast(model_lol_2,h=4*12,level=c(0.8,0.95))
x_forecast_2
plot(x_forecast_2)

true_ph=ts(lol[1:548,4],y)
plot(true_ph)
```
tide frequency: 1/12.5h
sunrise, sunset: 1/24h
average = 1/2 * (1/12.5 + 1/24)
period = 1 / average = 16.4h
75lags * 0.25h/lag = 18.75h

https://www.acs.psu.edu/drussell/demos/superposition/superposition.html
